[theme]
base = "light"
primaryColor = "#2563EB"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F8FE"
textColor = "#1D293D"
font = "sans-serif"
baseFontSize = 16
baseRadius = "0.375rem"
borderColor = "#E3EAF3"
headingFontSizes = ["2rem", "1.5rem", "1.125rem"]
codeFontSize = "0.875rem"

[theme.sidebar]
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F8FE"
textColor = "#1D293D"
primaryColor = "#2563EB"

[browser]
gatherUsageStats = false

[server]
address = "127.0.0.1"
headless = true
